// <auto-generated />
using MTSJira.Infrastructure.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MTSJira.Infrastructure.Database.Migrations
{
    [DbContext(typeof(JiraDbContext))]
    [Migration("20250916130321_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MTSJira.Domain.Entities.TaskData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignee")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("MTSJira.Domain.Entities.TaskRelationshipData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RelatedTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RelatedTaskId");

                    b.HasIndex("SourceTaskId");

                    b.ToTable("TaskRelationships");
                });

            modelBuilder.Entity("MTSJira.Domain.Entities.TaskData", b =>
                {
                    b.HasOne("MTSJira.Domain.Entities.TaskData", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("MTSJira.Domain.Entities.TaskRelationshipData", b =>
                {
                    b.HasOne("MTSJira.Domain.Entities.TaskData", "RelatedTask")
                        .WithMany("RelatedToTasks")
                        .HasForeignKey("RelatedTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTSJira.Domain.Entities.TaskData", "SourceTask")
                        .WithMany("RelatedTasks")
                        .HasForeignKey("SourceTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedTask");

                    b.Navigation("SourceTask");
                });

            modelBuilder.Entity("MTSJira.Domain.Entities.TaskData", b =>
                {
                    b.Navigation("RelatedTasks");

                    b.Navigation("RelatedToTasks");

                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
